/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xyz.room409.serif.serif_cli
import xyz.room409.serif.serif_shared.Greeting

class App {
    val greeting: String
        get() {
            return "from cli: " + Greeting().greeting()
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
