/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package xyz.room409.serif.serif_cli
import kotlin.test.Test
import kotlin.test.assertNotNull

class SerifCli {
    @Test fun testAppHasAVersion() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.version, "app should have a greeting")
    }
}
